table:
  name: v_meeting_clientPluginSettings
  schema: public
configuration:
  column_config: {}
  custom_column_names: {}
  custom_name: meeting_clientPluginSettings
  custom_root_fields: {}
select_permissions:
  - role: avx_client
    permission:
      columns:
        - dataChannels
        - name
        - settings
        - url
      filter:
        meetingId:
          _eq: X-Hasura-MeetingId
    comment: ""
