#!/bin/sh

write_config_file() {
  mkdir -p /etc/averox

        cat <<END > "${OP_CONFIG}"
// include default config from upstream
include "/usr/share/avx-apps-akka/conf/application.conf"

// you can customize everything here. API endpoint and secret have to be changed
// This file will not be overridden by packages

services {
  avxWebAPI=${API}
  sharedSecret=${SECRET}
}
END
}

case "$1" in
  install|upgrade|1|2)

    PACKAGE_CONFIG=/usr/share/avx-apps-akka/conf/application.conf
    OP_CONFIG=/etc/averox/avx-apps-akka.conf
    # this is for upgrading packages from old packaging system where operators had
    # to change the package config file
    if [ ! -f "${OP_CONFIG}" -a -f "${PACKAGE_CONFIG}" ]; then
      API=$(grep avxWebAPI "${PACKAGE_CONFIG}"  | sed 's/[^=]*=\s*//')
      SECRET=$(grep sharedSecret "${PACKAGE_CONFIG}"  | sed 's/[^=]*=\s*//')
      write_config_file
    fi
    # this is for fresh installs, where no config file exists
    if [ ! -f "${OP_CONFIG}" ]; then
      SECRET='"changeme"'
      API='"https://192.168.23.33/averox/api"'
      write_config_file
    fi
esac
